spring.application.name=Lab7
spring.mongodb.uri=mongodb://admin:password@localhost:27017/lab7_db?authSource=admin
jwt.secret=T0t_|<t0_3t0_c#it43t_t0t_R34lN|_c#0t|<i_P4can_|<0t0rI_$#4rIt_\/_|<0(\/)pUt3RN0(\/)_(\/)3(\/)3